# Generated by Django 5.2.3 on 2025-09-08 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0002_packageitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('vehicle_type', models.CharField(choices=[('car', 'Sedan Car'), ('suv', 'SUV'), ('bike', 'Bike'), ('bus', 'Mini Bus')], max_length=20)),
                ('pickup_location', models.CharField(max_length=200)),
                ('drop_location', models.CharField(blank=True, max_length=200, null=True)),
                ('booking_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
