# Generated by Django 5.2.3 on 2025-09-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0003_vehiclebooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='vehicles/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rating', models.PositiveIntegerField(default=0)),
                ('slug', models.SlugField(unique=True)),
                ('badge', models.CharField(blank=True, max_length=50, null=True)),
                ('badge_color', models.CharField(blank=True, choices=[('red', 'Red'), ('green', 'Green'), ('yellow', 'Yellow'), ('purple', 'Purple'), ('blue', 'Blue')], max_length=20, null=True)),
            ],
        ),
    ]
