# Generated by Django 5.2.3 on 2025-09-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0004_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('rating', models.IntegerField(default=3)),
                ('image', models.ImageField(upload_to='hotels/')),
            ],
        ),
    ]
