# Generated by Django 5.2.3 on 2025-09-08 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0007_food_foodorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
